/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Manage.ACMEApostas;
import Manage.Aposta;
import Manage.Apostador;
import java.util.InputMismatchException;

/**
 *
 * @author nico
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    private ACMEApostas acme;
    
    public JanelaPrincipal() {
        super();
        acme = new ACMEApostas();
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(3);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardJPanel = new javax.swing.JPanel();
        Fase1 = new javax.swing.JPanel();
        jtfNumerosApostas = new javax.swing.JTextField();
        jbtIniciar = new javax.swing.JButton();
        lbMegaSena = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMensagensTelaInicial = new javax.swing.JTextArea();
        jbtApostar = new javax.swing.JButton();
        jcbSurpresa = new javax.swing.JCheckBox();
        jbtSortear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Fase2 = new javax.swing.JPanel();
        jbtVoltarFase1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 490));
        setMinimumSize(new java.awt.Dimension(600, 490));

        cardJPanel.setMaximumSize(new java.awt.Dimension(600, 490));
        cardJPanel.setMinimumSize(new java.awt.Dimension(600, 490));
        cardJPanel.setPreferredSize(new java.awt.Dimension(600, 490));
        cardJPanel.setLayout(new java.awt.CardLayout());

        Fase1.setMaximumSize(new java.awt.Dimension(600, 490));
        Fase1.setMinimumSize(new java.awt.Dimension(600, 490));
        Fase1.setPreferredSize(new java.awt.Dimension(600, 490));

        jtfNumerosApostas.setEditable(false);
        jtfNumerosApostas.setEnabled(false);
        jtfNumerosApostas.setMaximumSize(new java.awt.Dimension(15, 24));
        jtfNumerosApostas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumerosApostasActionPerformed(evt);
            }
        });

        jbtIniciar.setText("Iniciar");
        jbtIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIniciarActionPerformed(evt);
            }
        });

        lbMegaSena.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lbMegaSena.setText("MegaSena");

        jtaMensagensTelaInicial.setEditable(false);
        jtaMensagensTelaInicial.setColumns(20);
        jtaMensagensTelaInicial.setRows(5);
        jtaMensagensTelaInicial.setEnabled(false);
        jtaMensagensTelaInicial.setMaximumSize(new java.awt.Dimension(220, 80));
        jtaMensagensTelaInicial.setMinimumSize(new java.awt.Dimension(220, 80));
        jScrollPane1.setViewportView(jtaMensagensTelaInicial);

        jbtApostar.setText("Apostar");
        jbtApostar.setEnabled(false);
        jbtApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtApostarActionPerformed(evt);
            }
        });

        jcbSurpresa.setText("Surpresa");
        jcbSurpresa.setEnabled(false);
        jcbSurpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSurpresaActionPerformed(evt);
            }
        });

        jbtSortear.setText("Sortear");
        jbtSortear.setEnabled(false);
        jbtSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSortearActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jtfNome.setEditable(false);
        jtfNome.setEnabled(false);
        jtfNome.setMaximumSize(new java.awt.Dimension(15, 24));

        jLabel2.setText("CPF:");

        jtfCPF.setEditable(false);
        jtfCPF.setEnabled(false);
        jtfCPF.setMaximumSize(new java.awt.Dimension(15, 24));

        jLabel3.setText("Numeros:");

        javax.swing.GroupLayout Fase1Layout = new javax.swing.GroupLayout(Fase1);
        Fase1.setLayout(Fase1Layout);
        Fase1Layout.setHorizontalGroup(
            Fase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fase1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jbtIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Fase1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(lbMegaSena)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fase1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(Fase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Fase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtSortear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Fase1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Fase1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumerosApostas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Fase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSurpresa)
                            .addComponent(jbtApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
        );
        Fase1Layout.setVerticalGroup(
            Fase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fase1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbMegaSena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtIniciar)
                .addGap(16, 16, 16)
                .addGroup(Fase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(Fase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumerosApostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtApostar)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSurpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtSortear)
                .addGap(50, 50, 50))
        );

        cardJPanel.add(Fase1, "card2");

        Fase2.setMaximumSize(new java.awt.Dimension(600, 490));
        Fase2.setMinimumSize(new java.awt.Dimension(600, 490));

        jbtVoltarFase1.setText("Voltar");
        jbtVoltarFase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarFase1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fase2Layout = new javax.swing.GroupLayout(Fase2);
        Fase2.setLayout(Fase2Layout);
        Fase2Layout.setHorizontalGroup(
            Fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fase2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jbtVoltarFase1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );
        Fase2Layout.setVerticalGroup(
            Fase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fase2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jbtVoltarFase1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        cardJPanel.add(Fase2, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNumerosApostasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumerosApostasActionPerformed

    }//GEN-LAST:event_jtfNumerosApostasActionPerformed

    private void jbtIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIniciarActionPerformed
        jtfNumerosApostas.setEditable(true);
        jtfNumerosApostas.setEnabled(true);
        jtaMensagensTelaInicial.setEnabled(true);
        jtaMensagensTelaInicial.setEnabled(true);
        jbtApostar.setEnabled(true);
        jcbSurpresa.setEnabled(true);
        jbtIniciar.setEnabled(false);
        jtfNome.setEnabled(true);
        jtfNome.setEditable(true);
        jtfCPF.setEnabled(true);
        jtfCPF.setEditable(true);
    }//GEN-LAST:event_jbtIniciarActionPerformed

    private void jbtApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtApostarActionPerformed
        if(jtfNome.getText().isEmpty() || jtfCPF.getText().isEmpty()) {
            jtaMensagensTelaInicial.append("Voce precisa inserir um nome e um cpf!\n");
            return;
        }
        
        if(jcbSurpresa.isSelected()) {
            //valor surpresa
            jtaMensagensTelaInicial.append("Surpresa\n");
            return;
        }
        
        Apostador apostador = new Apostador(jtfNome.getText().trim(), jtfCPF.getText().trim());
        acme.addApostador(apostador);
        
        try {
        String[] valores = jtfNumerosApostas.getText().toString().trim().split(" ");
        int[] aposta = new int[5];
        if(valores.length != 5) throw new InputMismatchException();
        for (int i = 0; i < 5; i++) {
            aposta[i] = Integer.parseInt(valores[i]);
            if(aposta[i] < 1 || aposta[i] > 50) throw new InputMismatchException();
        }
        
        Aposta a = new Aposta(apostador.getNome(), apostador.getCpf(), aposta);
        
        if(acme.addAposta(a)) {
            apostador.adicionarAposta(a);
            jtaMensagensTelaInicial.append("Aposta registrada:"
                    + "\nApostador: " + apostador.getNome() +
                    "\nCPF: " + apostador.getCpf() +
                    "\nAposta: " + a.printarAposta() + "\n");
        } else {
            jtaMensagensTelaInicial.append("Falha ao adicionar a aposta!");
        }
        
        jtfNome.setText("");
        jtfCPF.setText("");
        jtfNumerosApostas.setEnabled(true);
        jtfNumerosApostas.setEditable(true);
        jtfNumerosApostas.setText("");
        jcbSurpresa.setSelected(false);
        
        } catch (InputMismatchException e) {
            jtaMensagensTelaInicial.append("Falha! (Insira 5 numeros naturais menores que 50)\n");
            jtfNumerosApostas.setText("");
            e.printStackTrace();
        } catch (Exception e) {
            
        }
        
        
        
        
    }//GEN-LAST:event_jbtApostarActionPerformed

    private void jbtVoltarFase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarFase1ActionPerformed
        Fase2.setVisible(false);
        Fase1.setVisible(true);
    }//GEN-LAST:event_jbtVoltarFase1ActionPerformed

    private void jbtSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSortearActionPerformed
        Fase2.setVisible(true);
        Fase1.setVisible(false);
    }//GEN-LAST:event_jbtSortearActionPerformed

    private void jcbSurpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSurpresaActionPerformed
        if(!jtfNumerosApostas.getText().isEmpty()) {
            jtaMensagensTelaInicial.append("Voce ja esta fazendo uma aposta!\n");
            jcbSurpresa.setSelected(false);
            return;
        }
        

        if(jtfNumerosApostas.isEnabled()) {
        jtfNumerosApostas.setEnabled(false);
        jtfNumerosApostas.setEditable(false);
        } else {
        jtfNumerosApostas.setEnabled(true);
        jtfNumerosApostas.setEditable(true);
        }
    }//GEN-LAST:event_jcbSurpresaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fase1;
    private javax.swing.JPanel Fase2;
    private javax.swing.JPanel cardJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtApostar;
    private javax.swing.JButton jbtIniciar;
    private javax.swing.JButton jbtSortear;
    private javax.swing.JButton jbtVoltarFase1;
    private javax.swing.JCheckBox jcbSurpresa;
    private javax.swing.JTextArea jtaMensagensTelaInicial;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumerosApostas;
    private javax.swing.JLabel lbMegaSena;
    // End of variables declaration//GEN-END:variables
}
