/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Manage.ACMEApostas;
import Manage.Aposta;
import Manage.Apostador;
import Manage.Utils;
import javax.swing.JOptionPane;


public class JanelaPrincipalGUI extends javax.swing.JFrame {

    private ACMEApostas acme;
    
    public JanelaPrincipalGUI() {
        super();
        acme = new ACMEApostas();
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(3);
        setTitle("Fase 1: Apostas");
        setLocationRelativeTo(null);  
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardJPanel = new javax.swing.JPanel();
        FaseAposta = new javax.swing.JPanel();
        jbtIniciar = new javax.swing.JButton();
        lbMegaSena = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMensagensTelaInicial = new javax.swing.JTextArea();
        jbtApostar = new javax.swing.JButton();
        jcbSurpresa = new javax.swing.JCheckBox();
        jbtSortear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtLimpar = new javax.swing.JButton();
        jbtListar = new javax.swing.JButton();
        jtfNumero1 = new javax.swing.JTextField();
        jtfNumero2 = new javax.swing.JTextField();
        jtfNumero3 = new javax.swing.JTextField();
        jtfNumero4 = new javax.swing.JTextField();
        jtfNumero5 = new javax.swing.JTextField();
        FaseSorteioApuracao = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jbtAvancarFasePremiacao = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableNumeroRodadas = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableApostasVencedoras = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        JLableQtdRodadas = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableNumerosFrequencia = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        JLableQtdVencedores = new javax.swing.JLabel();
        jbtListarApostasApuracao = new javax.swing.JButton();
        FasePremiacao = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVencedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 490));

        cardJPanel.setMaximumSize(new java.awt.Dimension(600, 490));
        cardJPanel.setMinimumSize(new java.awt.Dimension(600, 490));
        cardJPanel.setPreferredSize(new java.awt.Dimension(600, 490));
        cardJPanel.setLayout(new java.awt.CardLayout());

        FaseAposta.setMaximumSize(new java.awt.Dimension(40, 15));
        FaseAposta.setMinimumSize(new java.awt.Dimension(40, 15));
        FaseAposta.setName(""); // NOI18N
        FaseAposta.setPreferredSize(new java.awt.Dimension(600, 490));

        jbtIniciar.setText("Iniciar");
        jbtIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIniciarActionPerformed(evt);
            }
        });

        lbMegaSena.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        lbMegaSena.setText("MegaSena");

        jtaMensagensTelaInicial.setEditable(false);
        jtaMensagensTelaInicial.setColumns(20);
        jtaMensagensTelaInicial.setRows(5);
        jtaMensagensTelaInicial.setEnabled(false);
        jtaMensagensTelaInicial.setMaximumSize(new java.awt.Dimension(220, 80));
        jtaMensagensTelaInicial.setMinimumSize(new java.awt.Dimension(220, 80));
        jScrollPane1.setViewportView(jtaMensagensTelaInicial);

        jbtApostar.setText("Apostar");
        jbtApostar.setEnabled(false);
        jbtApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtApostarActionPerformed(evt);
            }
        });

        jcbSurpresa.setText("Surpresa");
        jcbSurpresa.setEnabled(false);
        jcbSurpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSurpresaActionPerformed(evt);
            }
        });

        jbtSortear.setText("Sortear");
        jbtSortear.setEnabled(false);
        jbtSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSortearActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jtfNome.setEditable(false);
        jtfNome.setEnabled(false);
        jtfNome.setMaximumSize(new java.awt.Dimension(15, 24));

        jLabel2.setText("CPF:");

        jtfCPF.setEditable(false);
        jtfCPF.setEnabled(false);
        jtfCPF.setMaximumSize(new java.awt.Dimension(15, 24));

        jLabel3.setText("Numeros:");

        jbtLimpar.setText("Limpar");
        jbtLimpar.setEnabled(false);
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });

        jbtListar.setText("Listar");
        jbtListar.setEnabled(false);
        jbtListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListarActionPerformed(evt);
            }
        });

        jtfNumero1.setEditable(false);
        jtfNumero1.setEnabled(false);
        jtfNumero1.setMaximumSize(new java.awt.Dimension(40, 25));
        jtfNumero1.setMinimumSize(new java.awt.Dimension(40, 25));
        jtfNumero1.setName(""); // NOI18N
        jtfNumero1.setPreferredSize(new java.awt.Dimension(40, 25));

        jtfNumero2.setEditable(false);
        jtfNumero2.setEnabled(false);
        jtfNumero2.setMaximumSize(new java.awt.Dimension(40, 25));
        jtfNumero2.setMinimumSize(new java.awt.Dimension(40, 25));
        jtfNumero2.setName(""); // NOI18N
        jtfNumero2.setPreferredSize(new java.awt.Dimension(40, 25));

        jtfNumero3.setEditable(false);
        jtfNumero3.setEnabled(false);
        jtfNumero3.setMaximumSize(new java.awt.Dimension(40, 25));
        jtfNumero3.setMinimumSize(new java.awt.Dimension(40, 25));
        jtfNumero3.setName(""); // NOI18N
        jtfNumero3.setPreferredSize(new java.awt.Dimension(40, 25));

        jtfNumero4.setEditable(false);
        jtfNumero4.setEnabled(false);
        jtfNumero4.setMaximumSize(new java.awt.Dimension(40, 25));
        jtfNumero4.setMinimumSize(new java.awt.Dimension(40, 25));
        jtfNumero4.setName(""); // NOI18N
        jtfNumero4.setPreferredSize(new java.awt.Dimension(40, 25));

        jtfNumero5.setEditable(false);
        jtfNumero5.setEnabled(false);
        jtfNumero5.setMaximumSize(new java.awt.Dimension(40, 25));
        jtfNumero5.setMinimumSize(new java.awt.Dimension(40, 25));
        jtfNumero5.setName(""); // NOI18N
        jtfNumero5.setPreferredSize(new java.awt.Dimension(40, 25));

        javax.swing.GroupLayout FaseApostaLayout = new javax.swing.GroupLayout(FaseAposta);
        FaseAposta.setLayout(FaseApostaLayout);
        FaseApostaLayout.setHorizontalGroup(
            FaseApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FaseApostaLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(FaseApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FaseApostaLayout.createSequentialGroup()
                        .addComponent(jbtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jbtListar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtSortear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FaseApostaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FaseApostaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(jtfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FaseApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSurpresa)
                            .addComponent(jbtApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
            .addGroup(FaseApostaLayout.createSequentialGroup()
                .addGroup(FaseApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FaseApostaLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lbMegaSena))
                    .addGroup(FaseApostaLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jbtIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FaseApostaLayout.setVerticalGroup(
            FaseApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FaseApostaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbMegaSena)
                .addGap(4, 4, 4)
                .addComponent(jbtIniciar)
                .addGap(18, 18, 18)
                .addGroup(FaseApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FaseApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtApostar)
                    .addComponent(jLabel3)
                    .addComponent(jtfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSurpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FaseApostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSortear)
                    .addComponent(jbtLimpar)
                    .addComponent(jbtListar))
                .addGap(50, 50, 50))
        );

        cardJPanel.add(FaseAposta, "card2");

        FaseSorteioApuracao.setMaximumSize(new java.awt.Dimension(600, 490));
        FaseSorteioApuracao.setMinimumSize(new java.awt.Dimension(600, 490));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel4.setText("Apuracao");

        jbtAvancarFasePremiacao.setText("Premiação");
        jbtAvancarFasePremiacao.setMaximumSize(new java.awt.Dimension(70, 25));
        jbtAvancarFasePremiacao.setMinimumSize(new java.awt.Dimension(70, 25));
        jbtAvancarFasePremiacao.setPreferredSize(new java.awt.Dimension(70, 25));
        jbtAvancarFasePremiacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAvancarFasePremiacaoActionPerformed(evt);
            }
        });

        jLabel5.setText("Sorteados:");

        jTableNumeroRodadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Rodada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableNumeroRodadas);
        if (jTableNumeroRodadas.getColumnModel().getColumnCount() > 0) {
            jTableNumeroRodadas.getColumnModel().getColumn(0).setResizable(false);
            jTableNumeroRodadas.getColumnModel().getColumn(1).setResizable(false);
        }

        jTableApostasVencedoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aposta", "Numeros", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableApostasVencedoras.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTableApostasVencedoras);
        if (jTableApostasVencedoras.getColumnModel().getColumnCount() > 0) {
            jTableApostasVencedoras.getColumnModel().getColumn(0).setResizable(false);
            jTableApostasVencedoras.getColumnModel().getColumn(1).setResizable(false);
            jTableApostasVencedoras.getColumnModel().getColumn(2).setResizable(false);
            jTableApostasVencedoras.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel6.setText("Frequencias:");

        JLableQtdRodadas.setText("Rodadas:");

        jTableNumerosFrequencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Frequência"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableNumerosFrequencia.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTableNumerosFrequencia);
        if (jTableNumerosFrequencia.getColumnModel().getColumnCount() > 0) {
            jTableNumerosFrequencia.getColumnModel().getColumn(0).setResizable(false);
            jTableNumerosFrequencia.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel7.setText("Apostas Vencedoras:");

        JLableQtdVencedores.setText("Quantidade:");

        jbtListarApostasApuracao.setText("Todas Apostas");
        jbtListarApostasApuracao.setMaximumSize(new java.awt.Dimension(70, 24));
        jbtListarApostasApuracao.setMinimumSize(new java.awt.Dimension(70, 24));
        jbtListarApostasApuracao.setPreferredSize(new java.awt.Dimension(70, 24));
        jbtListarApostasApuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListarApostasApuracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(81, 81, 81)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(JLableQtdVencedores, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(66, 66, 66)
                                        .addComponent(JLableQtdRodadas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jbtListarApostasApuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAvancarFasePremiacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JLableQtdVencedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(JLableQtdRodadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAvancarFasePremiacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtListarApostasApuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout FaseSorteioApuracaoLayout = new javax.swing.GroupLayout(FaseSorteioApuracao);
        FaseSorteioApuracao.setLayout(FaseSorteioApuracaoLayout);
        FaseSorteioApuracaoLayout.setHorizontalGroup(
            FaseSorteioApuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FaseSorteioApuracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FaseSorteioApuracaoLayout.setVerticalGroup(
            FaseSorteioApuracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FaseSorteioApuracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardJPanel.add(FaseSorteioApuracao, "card3");

        jTableVencedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vencedor", "Prêmio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVencedores.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableVencedores);
        if (jTableVencedores.getColumnModel().getColumnCount() > 0) {
            jTableVencedores.getColumnModel().getColumn(0).setResizable(false);
            jTableVencedores.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FasePremiacaoLayout = new javax.swing.GroupLayout(FasePremiacao);
        FasePremiacao.setLayout(FasePremiacaoLayout);
        FasePremiacaoLayout.setHorizontalGroup(
            FasePremiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FasePremiacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FasePremiacaoLayout.setVerticalGroup(
            FasePremiacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FasePremiacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardJPanel.add(FasePremiacao, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListarActionPerformed
            new TabelaApostasGUI(acme, jbtListar);
            jbtListar.setEnabled(false);
    }//GEN-LAST:event_jbtListarActionPerformed

    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
        jtaMensagensTelaInicial.setText("");
    }//GEN-LAST:event_jbtLimparActionPerformed

    private void jbtSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSortearActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Voce deseja iniciar a fase de sorteio?", "Confirmacao", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            avancarFaseApostaParaSorteio();
            acme.setApostaPremiada(new Aposta());
            acme.apuracao();
            acme.preencherApostasVencedoras(jTableApostasVencedoras, JLableQtdVencedores);
            acme.preencherNumerosSorteados(jTableNumeroRodadas, JLableQtdRodadas);
            Utils.preencherNumerosOrdenadosPorFrequencia(jTableNumerosFrequencia, acme.getListaVetores());
        }
    }//GEN-LAST:event_jbtSortearActionPerformed

    private void jcbSurpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSurpresaActionPerformed
        if(!jtfNumero1.getText().isEmpty() ||
            !jtfNumero2.getText().isEmpty() ||
            !jtfNumero3.getText().isEmpty() ||
            !jtfNumero4.getText().isEmpty() ||
            !jtfNumero5.getText().isEmpty()) {
            jtaMensagensTelaInicial.append("Voce ja esta fazendo uma aposta!\n");
            jcbSurpresa.setSelected(false);
            return;
        }
        if(jtfNumero1.isEnabled()) {
            jtfNumero1.setEnabled(false);
            jtfNumero1.setEditable(false);
            jtfNumero2.setEnabled(false);
            jtfNumero2.setEditable(false);
            jtfNumero3.setEnabled(false);
            jtfNumero3.setEditable(false);
            jtfNumero4.setEnabled(false);
            jtfNumero4.setEditable(false);
            jtfNumero5.setEnabled(false);
            jtfNumero5.setEditable(false);
        } else {
            jtfNumero1.setEnabled(true);
            jtfNumero1.setEditable(true);
            jtfNumero2.setEnabled(true);
            jtfNumero2.setEditable(true);
            jtfNumero3.setEnabled(true);
            jtfNumero3.setEditable(true);
            jtfNumero4.setEnabled(true);
            jtfNumero4.setEditable(true);
            jtfNumero5.setEnabled(true);
            jtfNumero5.setEditable(true);
        }
    }//GEN-LAST:event_jcbSurpresaActionPerformed

    private void jbtApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtApostarActionPerformed
        if(jtfNome.getText().isEmpty() || jtfCPF.getText().isEmpty()) {
            jtaMensagensTelaInicial.append("Voce precisa inserir um nome e um cpf!\n");
            return;
        }

        Apostador apostador = acme.pesquisaApostador(jtfNome.getText().trim(), jtfCPF.getText().trim());

        if(jcbSurpresa.isSelected()) {
            Aposta a = new Aposta(jtfNome.getText(), jtfCPF.getText());
            acme.addAposta(a);
            apostador.adicionarAposta(a);
            jtaMensagensTelaInicial.append("Aposta Executada: " + a.getNumeros() + "\n");

            jbtSortear.setEnabled(true);
            return;
        }

        if(jtfNumero1.getText().isEmpty() ||
            jtfNumero2.getText().isEmpty() ||
            jtfNumero3.getText().isEmpty() ||
            jtfNumero4.getText().isEmpty() ||
            jtfNumero5.getText().isEmpty()) {
            jtaMensagensTelaInicial.append("Voce precisa inserir todos os numeros para apostar!\n");
            return;
        }

        String[] lista = {jtfNumero1.getText(),
            jtfNumero2.getText(),
            jtfNumero3.getText(),
            jtfNumero4.getText(),
            jtfNumero5.getText()};

        if(!acme.conferirStrings(lista))  {
            jtaMensagensTelaInicial.append("Todos os numeros precisam ser diferentes!\n");
            return;
        }

        try {
            int n1 = Integer.parseInt(jtfNumero1.getText());
            int n2 = Integer.parseInt(jtfNumero2.getText());
            int n3 = Integer.parseInt(jtfNumero3.getText());
            int n4 = Integer.parseInt(jtfNumero4.getText());
            int n5 = Integer.parseInt(jtfNumero5.getText());

            if(n1 > 50 || n1 < 1 || n2 > 50 || n2 < 1 ||
                n3 > 50 || n3 < 1 || n4 > 50 || n4 < 1 ||
                n5 > 50 || n5 < 1) throw new NumberFormatException();

            int[] vetor = {n1, n2, n3, n4 , n5};

            Aposta aposta = new Aposta(jtfNome.getText(), jtfCPF.getText(), vetor);

            acme.addAposta(aposta);
            apostador.adicionarAposta(aposta);

            jtaMensagensTelaInicial.append("Aposta Executada: " + aposta.getNumeros() + "\n");
            jtfNumero1.setText("");
            jtfNumero2.setText("");
            jtfNumero3.setText("");
            jtfNumero4.setText("");
            jtfNumero5.setText("");

        } catch(NumberFormatException e) {
            jtaMensagensTelaInicial.append("Apenas numeros naturais entre 1 e 50!\n");
        } catch(Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jbtApostarActionPerformed

    private void jbtIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIniciarActionPerformed
        jtfNumero1.setEnabled(true);
        jtfNumero1.setEditable(true);
        jtfNumero2.setEnabled(true);
        jtfNumero2.setEditable(true);
        jtfNumero3.setEnabled(true);
        jtfNumero3.setEditable(true);
        jtfNumero4.setEnabled(true);
        jtfNumero4.setEditable(true);
        jtfNumero5.setEnabled(true);
        jtfNumero5.setEditable(true);
        jtaMensagensTelaInicial.setEnabled(true);
        jtaMensagensTelaInicial.setEnabled(true);
        jbtApostar.setEnabled(true);
        jcbSurpresa.setEnabled(true);
        jbtIniciar.setEnabled(false);
        jtfNome.setEnabled(true);
        jtfNome.setEditable(true);
        jtfCPF.setEnabled(true);
        jtfCPF.setEditable(true);
        jbtLimpar.setEnabled(true);
        jbtListar.setEnabled(true);
    }//GEN-LAST:event_jbtIniciarActionPerformed

    private void jbtAvancarFasePremiacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAvancarFasePremiacaoActionPerformed
       FaseSorteioApuracao.setVisible(false);
       FasePremiacao.setVisible(true);
       Utils.preencherNumerosOrdenadosPorFrequencia(jTableVencedores, acme.getListaVetores());
       Utils.centralizarConteudoTabela(jTableVencedores);
    }//GEN-LAST:event_jbtAvancarFasePremiacaoActionPerformed

    private void jbtListarApostasApuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListarApostasApuracaoActionPerformed
        new TabelaApostasGUI(acme, jbtListarApostasApuracao);
        jbtListarApostasApuracao.setEnabled(false);
    }//GEN-LAST:event_jbtListarApostasApuracaoActionPerformed

    public void avancarFaseApostaParaSorteio() {
        FaseAposta.setVisible(false);
        FaseSorteioApuracao.setVisible(true);
        setTitle("Fase 2: Sorteio");
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FaseAposta;
    private javax.swing.JPanel FasePremiacao;
    private javax.swing.JPanel FaseSorteioApuracao;
    private javax.swing.JLabel JLableQtdRodadas;
    private javax.swing.JLabel JLableQtdVencedores;
    private javax.swing.JPanel cardJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableApostasVencedoras;
    private javax.swing.JTable jTableNumeroRodadas;
    private javax.swing.JTable jTableNumerosFrequencia;
    private javax.swing.JTable jTableVencedores;
    private javax.swing.JButton jbtApostar;
    private javax.swing.JButton jbtAvancarFasePremiacao;
    private javax.swing.JButton jbtIniciar;
    private javax.swing.JButton jbtLimpar;
    private javax.swing.JButton jbtListar;
    private javax.swing.JButton jbtListarApostasApuracao;
    private javax.swing.JButton jbtSortear;
    private javax.swing.JCheckBox jcbSurpresa;
    private javax.swing.JTextArea jtaMensagensTelaInicial;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero1;
    private javax.swing.JTextField jtfNumero2;
    private javax.swing.JTextField jtfNumero3;
    private javax.swing.JTextField jtfNumero4;
    private javax.swing.JTextField jtfNumero5;
    private javax.swing.JLabel lbMegaSena;
    // End of variables declaration//GEN-END:variables
}
